// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "pull-request-service/internal/model"
)

// PRService is an autogenerated mock type for the PRService type
type PRService struct {
	mock.Mock
}

// CreatePR provides a mock function with given fields: ctx, input
func (_m *PRService) CreatePR(ctx context.Context, input model.PullRequest) (model.PullRequest, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreatePR")
	}

	var r0 model.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.PullRequest) (model.PullRequest, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.PullRequest) model.PullRequest); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(model.PullRequest)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.PullRequest) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListAssignedToUser provides a mock function with given fields: ctx, userID
func (_m *PRService) ListAssignedToUser(ctx context.Context, userID string) ([]model.PullRequestShort, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListAssignedToUser")
	}

	var r0 []model.PullRequestShort
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.PullRequestShort, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.PullRequestShort); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.PullRequestShort)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MergePR provides a mock function with given fields: ctx, prID
func (_m *PRService) MergePR(ctx context.Context, prID string) (model.PullRequest, error) {
	ret := _m.Called(ctx, prID)

	if len(ret) == 0 {
		panic("no return value specified for MergePR")
	}

	var r0 model.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.PullRequest, error)); ok {
		return rf(ctx, prID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.PullRequest); ok {
		r0 = rf(ctx, prID)
	} else {
		r0 = ret.Get(0).(model.PullRequest)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, prID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReassignReviewer provides a mock function with given fields: ctx, prID, oldUserID
func (_m *PRService) ReassignReviewer(ctx context.Context, prID string, oldUserID string) (model.PullRequest, string, error) {
	ret := _m.Called(ctx, prID, oldUserID)

	if len(ret) == 0 {
		panic("no return value specified for ReassignReviewer")
	}

	var r0 model.PullRequest
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (model.PullRequest, string, error)); ok {
		return rf(ctx, prID, oldUserID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) model.PullRequest); ok {
		r0 = rf(ctx, prID, oldUserID)
	} else {
		r0 = ret.Get(0).(model.PullRequest)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) string); ok {
		r1 = rf(ctx, prID, oldUserID)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = rf(ctx, prID, oldUserID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewPRService creates a new instance of PRService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPRService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PRService {
	mock := &PRService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
