// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "pull-request-service/internal/model"
)

// UserService is an autogenerated mock type for the UserService type
type UserService struct {
	mock.Mock
}

// SetIsActive provides a mock function with given fields: ctx, userID, isActive
func (_m *UserService) SetIsActive(ctx context.Context, userID string, isActive bool) (model.User, error) {
	ret := _m.Called(ctx, userID, isActive)

	if len(ret) == 0 {
		panic("no return value specified for SetIsActive")
	}

	var r0 model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) (model.User, error)); ok {
		return rf(ctx, userID, isActive)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) model.User); ok {
		r0 = rf(ctx, userID, isActive)
	} else {
		r0 = ret.Get(0).(model.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, bool) error); ok {
		r1 = rf(ctx, userID, isActive)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserService creates a new instance of UserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserService {
	mock := &UserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
