// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	model "pull-request-service/internal/model"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// PRRepository is an autogenerated mock type for the PRRepository type
type PRRepository struct {
	mock.Mock
}

// CreatePRWithReviewers provides a mock function with given fields: ctx, pr, reviewerIDs
func (_m *PRRepository) CreatePRWithReviewers(ctx context.Context, pr model.PullRequest, reviewerIDs []string) (model.PullRequest, error) {
	ret := _m.Called(ctx, pr, reviewerIDs)

	if len(ret) == 0 {
		panic("no return value specified for CreatePRWithReviewers")
	}

	var r0 model.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.PullRequest, []string) (model.PullRequest, error)); ok {
		return rf(ctx, pr, reviewerIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.PullRequest, []string) model.PullRequest); ok {
		r0 = rf(ctx, pr, reviewerIDs)
	} else {
		r0 = ret.Get(0).(model.PullRequest)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.PullRequest, []string) error); ok {
		r1 = rf(ctx, pr, reviewerIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOpenPRsByReviewers provides a mock function with given fields: ctx, reviewerIDs
func (_m *PRRepository) GetOpenPRsByReviewers(ctx context.Context, reviewerIDs []string) (map[string][]string, error) {
	ret := _m.Called(ctx, reviewerIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetOpenPRsByReviewers")
	}

	var r0 map[string][]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) (map[string][]string, error)); ok {
		return rf(ctx, reviewerIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) map[string][]string); ok {
		r0 = rf(ctx, reviewerIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, reviewerIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPR provides a mock function with given fields: ctx, prID
func (_m *PRRepository) GetPR(ctx context.Context, prID string) (model.PullRequest, error) {
	ret := _m.Called(ctx, prID)

	if len(ret) == 0 {
		panic("no return value specified for GetPR")
	}

	var r0 model.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.PullRequest, error)); ok {
		return rf(ctx, prID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.PullRequest); ok {
		r0 = rf(ctx, prID)
	} else {
		r0 = ret.Get(0).(model.PullRequest)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, prID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetReviewerStats provides a mock function with given fields: ctx
func (_m *PRRepository) GetReviewerStats(ctx context.Context) ([]model.StatsDTO, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetReviewerStats")
	}

	var r0 []model.StatsDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.StatsDTO, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.StatsDTO); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.StatsDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListAssignedToUser provides a mock function with given fields: ctx, userID
func (_m *PRRepository) ListAssignedToUser(ctx context.Context, userID string) ([]model.PullRequestShort, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListAssignedToUser")
	}

	var r0 []model.PullRequestShort
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.PullRequestShort, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.PullRequestShort); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.PullRequestShort)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarkMerged provides a mock function with given fields: ctx, prID, mergedAt
func (_m *PRRepository) MarkMerged(ctx context.Context, prID string, mergedAt time.Time) (model.PullRequest, error) {
	ret := _m.Called(ctx, prID, mergedAt)

	if len(ret) == 0 {
		panic("no return value specified for MarkMerged")
	}

	var r0 model.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) (model.PullRequest, error)); ok {
		return rf(ctx, prID, mergedAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) model.PullRequest); ok {
		r0 = rf(ctx, prID, mergedAt)
	} else {
		r0 = ret.Get(0).(model.PullRequest)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = rf(ctx, prID, mergedAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReassignReviewer provides a mock function with given fields: ctx, prID, oldUserID, newUserID
func (_m *PRRepository) ReassignReviewer(ctx context.Context, prID string, oldUserID string, newUserID string) (model.PullRequest, error) {
	ret := _m.Called(ctx, prID, oldUserID, newUserID)

	if len(ret) == 0 {
		panic("no return value specified for ReassignReviewer")
	}

	var r0 model.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (model.PullRequest, error)); ok {
		return rf(ctx, prID, oldUserID, newUserID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) model.PullRequest); ok {
		r0 = rf(ctx, prID, oldUserID, newUserID)
	} else {
		r0 = ret.Get(0).(model.PullRequest)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, prID, oldUserID, newUserID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveReviewer provides a mock function with given fields: ctx, prID, reviewerID
func (_m *PRRepository) RemoveReviewer(ctx context.Context, prID string, reviewerID string) error {
	ret := _m.Called(ctx, prID, reviewerID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveReviewer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, prID, reviewerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPRRepository creates a new instance of PRRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPRRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PRRepository {
	mock := &PRRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
