// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	model "pull-request-service/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// TeamRepository is an autogenerated mock type for the TeamRepository type
type TeamRepository struct {
	mock.Mock
}

// CreateTeamWithMembers provides a mock function with given fields: ctx, team
func (_m *TeamRepository) CreateTeamWithMembers(ctx context.Context, team model.Team) (model.Team, error) {
	ret := _m.Called(ctx, team)

	if len(ret) == 0 {
		panic("no return value specified for CreateTeamWithMembers")
	}

	var r0 model.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Team) (model.Team, error)); ok {
		return rf(ctx, team)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Team) model.Team); ok {
		r0 = rf(ctx, team)
	} else {
		r0 = ret.Get(0).(model.Team)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Team) error); ok {
		r1 = rf(ctx, team)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTeamByName provides a mock function with given fields: ctx, name
func (_m *TeamRepository) GetTeamByName(ctx context.Context, name string) (model.Team, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamByName")
	}

	var r0 model.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Team, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Team); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(model.Team)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTeamRepository creates a new instance of TeamRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTeamRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TeamRepository {
	mock := &TeamRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
